WriteMappingToWorksheet: 2
StartAtLine: 2
UnknownValueHandling: Leave
Default: DefaultValue
Maps:
  map1:
    value 1: 0
    value 2: 1
  map2:
    value 1: 1
    value 2: 0
MapForColumn:
  map1:
  - 1
  - 2
  map2:
  - 3-5
MapWorksheet: 1
